<?php
namespace App;
use App\http\MyContext;

class MyRouter extends \FastRoute\RouteCollector
{
    private $handlers = [];
    public function add($httpMethod, $route, ...$handlers)
    {
        $this->handlers = array_merge($this->handlers, $handlers);
        $getHandlers = $this->handlers;
        $func=function (MyContext $context) use($getHandlers){
            foreach ($getHandlers as $handler) {
                $ret = $handler($context);
                if ($ret) {
                    $context->setHandlerResult($ret);
                }
                if ($context->getState() == 0) {
                    break;
                }
            }
        };
        parent::addRoute($httpMethod, $route, $func); // TODO: Change the autogenerated stub
    }

    public function Use($middleware)
    {
        $this->handlers[] = $middleware;
    }
}